# Generated by Django 3.0.4 on 2020-04-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empleado', models.CharField(max_length=50, verbose_name='Nombres')),
                ('ape_empleado', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('cedu_empleado', models.CharField(max_length=15, verbose_name='Identificación')),
                ('celu_empleado', models.CharField(max_length=10, verbose_name='Numero de Celular')),
                ('email_empleado', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado_empleado', models.BooleanField(verbose_name='Actualmente Contratado')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.FloatField()),
                ('observacion', models.CharField(max_length=100)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tipo_contrato', models.CharField(max_length=50, verbose_name='Tipo de Contrato')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Hojas_Vida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deta_hoja_vida', models.FileField(upload_to='hojasvida', verbose_name='Detalle hoja de vida')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_Laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empresa', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('deta_experiencia', models.CharField(max_length=50, verbose_name='Detalle de la experiencia')),
                ('dura_experiencia', models.IntegerField(verbose_name='Duracion de la experiencia')),
                ('fech_inicio_expe', models.DateField(verbose_name='Fecha de Inicio')),
                ('fech_fin_expe', models.DateField(verbose_name='Fecha Final')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_instituto', models.CharField(max_length=50, verbose_name='Nombre de la Institución')),
                ('niv_educativo', models.CharField(max_length=50, verbose_name='Nivel Educativo')),
                ('deta_educacion', models.CharField(max_length=50, verbose_name='Programa')),
                ('cursa_educacion', models.BooleanField(verbose_name='Cursando Actualmente')),
                ('fech_inicio_edu', models.DateField(verbose_name='Fecha de Inicio')),
                ('fech_fin_edu', models.DateField(verbose_name='Fecha Final')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contratos_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_contratos_doc', models.FileField(upload_to='contratos', verbose_name='Contrato')),
                ('fech_inicio_contrato', models.DateField(verbose_name='Fecha de Inicio')),
                ('fech_fin_contrato', models.DateField(verbose_name='Fecha Final')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion_Laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deta_certificacion_labo', models.FileField(upload_to='certificacion', verbose_name='Documento de la certificacion')),
                ('experiencia_laboral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Experiencia_Laboral')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_cargo_empleado', models.CharField(max_length=50, verbose_name='Cargo')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
    ]
