# Generated by Django 3.0.4 on 2020-04-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REGEmpleados', '0002_auto_20200412_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_empleado', models.CharField(max_length=50, verbose_name='Cargo')),
                ('tipo_contrato', models.CharField(max_length=50, verbose_name='Tipo de Contrato')),
                ('contrato_doc', models.FileField(upload_to='contratos', verbose_name='Contrato')),
                ('fech_inicio_contrato', models.DateField(verbose_name='Fecha de Inicio')),
                ('fech_fin_contrato', models.DateField(verbose_name='Fecha Final')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos_Soporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('documento_soporte', models.FileField(upload_to='documentos_soporte', verbose_name='Documento')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REGEmpleados.Empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificacion_laboral',
            name='experiencia_laboral',
        ),
        migrations.RemoveField(
            model_name='contratos_doc',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='hojas_vida',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='tipo_contrato',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='experiencia_laboral',
            name='deta_experiencia',
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='cargo_experiencia',
            field=models.CharField(default=None, max_length=50, verbose_name='Cargo desempeñado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='certificacion_labo',
            field=models.FileField(default=None, upload_to='certificacion', verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cargo_Empleado',
        ),
        migrations.DeleteModel(
            name='Certificacion_Laboral',
        ),
        migrations.DeleteModel(
            name='Contratos_Doc',
        ),
        migrations.DeleteModel(
            name='Hojas_Vida',
        ),
        migrations.DeleteModel(
            name='Tipo_Contrato',
        ),
    ]
