# Generated by Django 3.0.4 on 2020-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REGEmpleados', '0003_auto_20200413_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='sueldo',
            field=models.CharField(default=None, max_length=10, verbose_name='Sueldo'),
            preserve_default=False,
        ),
    ]
