# Generated by Django 3.0.4 on 2020-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REGContracEx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos_externos',
            old_name='tipo_contrato',
            new_name='clase_contrato',
        ),
        migrations.AddField(
            model_name='contratos_externos',
            name='supervisor',
            field=models.CharField(default=None, max_length=80, verbose_name='Supervisor'),
            preserve_default=False,
        ),
    ]
